name: character_parser
version: 0.2.0
# author: Demis Bellot <demis.bellot@gmail.com>
description: Parse Dart one character at a time to look for snippets in Templates
environment:
  sdk: "<3.0.0"
homepage: https://github.com/dartist/character_parser
dev_dependencies:
  test: any
  pedantic:

#dependencies:
#  unittest: any